name: ConSPIRe
version: 0.1.0.0
github: "ricffb/conspire"
license: BSD3
author: "Henrik Wachowitz"
maintainer: "henrik.wachowitz@tum.de"
copyright: "2021 Henrik Wachowitz"

extra-source-files:
  - README.md
  - ChangeLog.md
  - parser/CSPM/Parser.y
  - parser/CSPM/Lexer.x

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/cspire#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6
  - unordered-containers == 0.2.15.0
  - mtl
  - array >= 0.5.4
  - transformers == 0.5.6.2
  - extra == 1.7.10

build-tools:
  - alex
  - happy

library:
  source-dirs:
    - src
    - parser

executables:
  cspir:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ConSPIRe

tests:
  cspire-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ConSPIRe
      - hspec
