name: cspire
version: 0.1.0.0
github: "githubuser/cspire"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md
  - parser/cspm.y

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/cspire#readme>

dependencies:
  - base >= 4.7 && < 5
  - CSPM-Frontend == 0.12.1.1
  - containers >= 0.6
  - mtl

build-tools:
  - alex
  - happy

library:
  source-dirs:
    - src
    - parser

executables:
  cspire-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cspire

tests:
  cspire-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cspire
